USE [master]
GO
/****** Object:  Database [Fixinfo]    Script Date: 27/02/2026 14:59:54 ******/
CREATE DATABASE [Fixinfo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'fixinfo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\fixinfo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'fixinfo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\fixinfo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Fixinfo] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Fixinfo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Fixinfo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Fixinfo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Fixinfo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Fixinfo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Fixinfo] SET ARITHABORT OFF 
GO
ALTER DATABASE [Fixinfo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Fixinfo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Fixinfo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Fixinfo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Fixinfo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Fixinfo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Fixinfo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Fixinfo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Fixinfo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Fixinfo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Fixinfo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Fixinfo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Fixinfo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Fixinfo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Fixinfo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Fixinfo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Fixinfo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Fixinfo] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Fixinfo] SET  MULTI_USER 
GO
ALTER DATABASE [Fixinfo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Fixinfo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Fixinfo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Fixinfo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Fixinfo] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Fixinfo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Fixinfo] SET QUERY_STORE = ON
GO
ALTER DATABASE [Fixinfo] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Fixinfo]
GO
/****** Object:  Table [dbo].[Inter]    Script Date: 27/02/2026 14:59:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Inter](
	[ID_INTER] [int] IDENTITY(1,1) NOT NULL,
	[Date_Inter] [date] NOT NULL,
	[IDMATERIEL] [int] NOT NULL,
	[Prix] [money] NOT NULL,
	[Comment] [text] NULL,
 CONSTRAINT [PK_Inter] PRIMARY KEY CLUSTERED 
(
	[ID_INTER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Login]    Script Date: 27/02/2026 14:59:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Login](
	[ID_LOGIN] [int] IDENTITY(1,1) NOT NULL,
	[Nom] [varchar](50) NOT NULL,
	[PWD] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Login] PRIMARY KEY CLUSTERED 
(
	[ID_LOGIN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Materiel]    Script Date: 27/02/2026 14:59:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Materiel](
	[ID_MATOS] [int] IDENTITY(1,1) NOT NULL,
	[Nom] [varchar](50) NOT NULL,
	[Prix] [money] NOT NULL,
	[Description] [text] NULL,
	[DateInstall] [date] NOT NULL,
	[MTBF] [int] NOT NULL,
 CONSTRAINT [PK_Materiel] PRIMARY KEY CLUSTERED 
(
	[ID_MATOS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Inter] ON 

INSERT [dbo].[Inter] ([ID_INTER], [Date_Inter], [IDMATERIEL], [Prix], [Comment]) VALUES (2, CAST(N'2023-12-19' AS Date), 2, 50.0000, N'ok')
INSERT [dbo].[Inter] ([ID_INTER], [Date_Inter], [IDMATERIEL], [Prix], [Comment]) VALUES (3, CAST(N'2025-12-03' AS Date), 4, 25.0000, N'oui')
INSERT [dbo].[Inter] ([ID_INTER], [Date_Inter], [IDMATERIEL], [Prix], [Comment]) VALUES (4, CAST(N'2025-11-29' AS Date), 3, 80.0000, N'yes')
INSERT [dbo].[Inter] ([ID_INTER], [Date_Inter], [IDMATERIEL], [Prix], [Comment]) VALUES (5, CAST(N'2026-01-02' AS Date), 2, 125.0000, N'marche pas')
SET IDENTITY_INSERT [dbo].[Inter] OFF
GO
SET IDENTITY_INSERT [dbo].[Login] ON 

INSERT [dbo].[Login] ([ID_LOGIN], [Nom], [PWD]) VALUES (1, N'steph', N'steph')
INSERT [dbo].[Login] ([ID_LOGIN], [Nom], [PWD]) VALUES (2, N'yael', N'yayo')
INSERT [dbo].[Login] ([ID_LOGIN], [Nom], [PWD]) VALUES (3, N'ploukof', N'anticonstitutionnellement')
INSERT [dbo].[Login] ([ID_LOGIN], [Nom], [PWD]) VALUES (4, N'root', N'root2')
INSERT [dbo].[Login] ([ID_LOGIN], [Nom], [PWD]) VALUES (5, N'a', N'a')
SET IDENTITY_INSERT [dbo].[Login] OFF
GO
SET IDENTITY_INSERT [dbo].[Materiel] ON 

INSERT [dbo].[Materiel] ([ID_MATOS], [Nom], [Prix], [Description], [DateInstall], [MTBF]) VALUES (1, N'PC8874', 1200.0000, N'beau', CAST(N'2022-05-12' AS Date), 60)
INSERT [dbo].[Materiel] ([ID_MATOS], [Nom], [Prix], [Description], [DateInstall], [MTBF]) VALUES (2, N'Screen Logi 1', 131.0000, N'marche', CAST(N'2024-02-19' AS Date), 80)
INSERT [dbo].[Materiel] ([ID_MATOS], [Nom], [Prix], [Description], [DateInstall], [MTBF]) VALUES (3, N'printepso', 5.0000, N'ok', CAST(N'2020-12-23' AS Date), 72)
INSERT [dbo].[Materiel] ([ID_MATOS], [Nom], [Prix], [Description], [DateInstall], [MTBF]) VALUES (4, N'SOuris moiaoui', 2.0000, N'miaoumiaou', CAST(N'2025-05-29' AS Date), 12)
INSERT [dbo].[Materiel] ([ID_MATOS], [Nom], [Prix], [Description], [DateInstall], [MTBF]) VALUES (5, N'nouvmat', 18.0000, N'beau matos', CAST(N'2023-05-08' AS Date), 60)
INSERT [dbo].[Materiel] ([ID_MATOS], [Nom], [Prix], [Description], [DateInstall], [MTBF]) VALUES (6, N'PR1000', 50.0000, N'cool printer', CAST(N'2024-11-25' AS Date), 36)
INSERT [dbo].[Materiel] ([ID_MATOS], [Nom], [Prix], [Description], [DateInstall], [MTBF]) VALUES (7, N'Screen RPX', 80.0000, N'sympa ecran cool ', CAST(N'2026-02-25' AS Date), 89)
SET IDENTITY_INSERT [dbo].[Materiel] OFF
GO
ALTER TABLE [dbo].[Inter]  WITH CHECK ADD  CONSTRAINT [FK_Inter_Materiel] FOREIGN KEY([IDMATERIEL])
REFERENCES [dbo].[Materiel] ([ID_MATOS])
GO
ALTER TABLE [dbo].[Inter] CHECK CONSTRAINT [FK_Inter_Materiel]
GO
USE [master]
GO
ALTER DATABASE [Fixinfo] SET  READ_WRITE 
GO
